package iut;
// Generated 14 janv. 2010 16:48:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String name;
     private Set<Category> categories = new HashSet<Category>(0);
     private Set<Document> documents = new HashSet<Document>(0);

    public Category() {
    }

	
    public Category(String name) {
        this.name = name;
    }
    public Category(Category category, String name, Set<Category> categories, Set<Document> documents) {
       this.category = category;
       this.name = name;
       this.categories = categories;
       this.documents = documents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }
    public Set<Document> getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set<Document> documents) {
        this.documents = documents;
    }




}


