package iut;
// Generated 14 janv. 2010 16:48:02 by Hibernate Tools 3.2.1.GA



/**
 * Commentary generated by hbm2java
 */
public class Commentary  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String commentary;

    public Commentary() {
    }

	
    public Commentary(Users users) {
        this.users = users;
    }
    public Commentary(Users users, String commentary) {
       this.users = users;
       this.commentary = commentary;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCommentary() {
        return this.commentary;
    }
    
    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }




}


