package iut;
// Generated 14 janv. 2010 16:48:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private char sex;
     private String firstname;
     private String lastname;
     private Date birthdate;
     private String email;
     private Set<Commentary> commentaries = new HashSet<Commentary>(0);
     private Set<Document> documents = new HashSet<Document>(0);

    public Users() {
    }

	
    public Users(char sex, String firstname, String lastname, String email) {
        this.sex = sex;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
    }
    public Users(char sex, String firstname, String lastname, Date birthdate, String email, Set<Commentary> commentaries, Set<Document> documents) {
       this.sex = sex;
       this.firstname = firstname;
       this.lastname = lastname;
       this.birthdate = birthdate;
       this.email = email;
       this.commentaries = commentaries;
       this.documents = documents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public char getSex() {
        return this.sex;
    }
    
    public void setSex(char sex) {
        this.sex = sex;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Commentary> getCommentaries() {
        return this.commentaries;
    }
    
    public void setCommentaries(Set<Commentary> commentaries) {
        this.commentaries = commentaries;
    }
    public Set<Document> getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set<Document> documents) {
        this.documents = documents;
    }




}


